function [PhosphorylationRateModulatorValue]=PhosphorylationRateModulator(CalciumValue,PowerConstantofPhosphorylation,ConstantofPhosphorylation)

PhosphorylationRateModulatorValue=(CalciumValue^PowerConstantofPhosphorylation)/(ConstantofPhosphorylation+CalciumValue^PowerConstantofPhosphorylation);